TripMapR/travelogue/urls.py
from django.conf.urls import *
from django.views.generic import RedirectView
from django.core.urlresolvers import reverse_lazy

from .views import PhotoListView, PhotoDetailView, TravelogueListView, \
    TravelogueDetailView, PhotoArchiveIndexView, PhotoDateDetailView, PhotoDayArchiveView, \
    PhotoYearArchiveView, PhotoMonthArchiveView, TravelogueArchiveIndexView, TravelogueYearArchiveView, \
    TravelogueDateDetailView, TravelogueDayArchiveView, TravelogueMonthArchiveView, TravelogueDateDetailOldView, \
    TravelogueDayArchiveOldView, TravelogueMonthArchiveOldView, PhotoDateDetailOldView, \
    PhotoDayArchiveOldView, PhotoMonthArchiveOldView

"""NOTE: the url names are changing. In the long term, I want to remove the 'pl-'
prefix on all urls, and instead rely on an application namespace 'travelogue'.

At the same time, I want to change some URL patterns, e.g. for pagination. Changing the urls
twice within a few releases, could be confusing, so instead I am updating URLs bit by bit.

The new style will coexist with the existing 'pl-' prefix for a couple of releases.

"""


urlpatterns = patterns('',

                       url(r'^travelogue/(?P<year>\d{4})/(?P<month>[0-9]{2})/(?P<day>\w{1,2})/(?P<slug>[\-\d\w]+)/$',
                           TravelogueDateDetailView.as_view(month_format='%m'),
                           name='travelogue-detail'),
                       url(r'^travelogue/(?P<year>\d{4})/(?P<month>[0-9]{2})/(?P<day>\w{1,2})/$',
                           TravelogueDayArchiveView.as_view(month_format='%m'),
                           name='travelogue-archive-day'),
                       url(r'^travelogue/(?P<year>\d{4})/(?P<month>[0-9]{2})/$',
                           TravelogueMonthArchiveView.as_view(month_format='%m'),
                           name='travelogue-archive-month'),
                       url(r'^travelogue/(?P<year>\d{4})/$',
                           TravelogueYearArchiveView.as_view(),
                           name='pl-travelogue-archive-year'),
                       url(r'^travelogue/$',
                           TravelogueArchiveIndexView.as_view(),
                           name='pl-travelogue-archive'),
                       url(r'^$',
                           RedirectView.as_view(url=reverse_lazy('travelogue:pl-travelogue-archive')),
                           name='pl-travelogue-root'),
                       url(r'^travelogue/(?P<slug>[\-\d\w]+)/$',
                           TravelogueDetailView.as_view(), name='pl-travelogue'),
                       url(r'^traveloguelist/$',
                           TravelogueListView.as_view(),
                           name='travelogue-list'),

                       url(r'^photo/(?P<year>\d{4})/(?P<month>[0-9]{2})/(?P<day>\w{1,2})/(?P<slug>[\-\d\w]+)/$',
                           PhotoDateDetailView.as_view(month_format='%m'),
                           name='photo-detail'),
                       url(r'^photo/(?P<year>\d{4})/(?P<month>[0-9]{2})/(?P<day>\w{1,2})/$',
                           PhotoDayArchiveView.as_view(month_format='%m'),
                           name='photo-archive-day'),
                       url(r'^photo/(?P<year>\d{4})/(?P<month>[0-9]{2})/$',
                           PhotoMonthArchiveView.as_view(month_format='%m'),
                           name='photo-archive-month'),
                       url(r'^photo/(?P<year>\d{4})/$',
                           PhotoYearArchiveView.as_view(),
                           name='pl-photo-archive-year'),
                       url(r'^photo/$',
                           PhotoArchiveIndexView.as_view(),
                           name='pl-photo-archive'),

                       url(r'^photo/(?P<slug>[\-\d\w]+)/$',
                           PhotoDetailView.as_view(),
                           name='pl-photo'),
                       url(r'^photolist/$',
                           PhotoListView.as_view(),
                           name='photo-list'),

                       # Deprecated URLs.
                       url(r'^travelogue/page/(?P<page>[0-9]+)/$',
                           TravelogueListView.as_view(),
                           {'deprecated_pagination': True},
                           name='pl-travelogue-list'),
                       url(r'^photo/page/(?P<page>[0-9]+)/$',
                           PhotoListView.as_view(),
                           {'deprecated_pagination': True},
                           name='pl-photo-list'),

                       url(r'^travelogue/(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\w{1,2})/(?P<slug>[\-\d\w]+)/$',
                           TravelogueDateDetailOldView.as_view(),
                           name='pl-travelogue-detail'),
                       url(r'^travelogue/(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\w{1,2})/$',
                           TravelogueDayArchiveOldView.as_view(),
                           name='pl-travelogue-archive-day'),
                       url(r'^travelogue/(?P<year>\d{4})/(?P<month>[a-z]{3})/$',
                           TravelogueMonthArchiveOldView.as_view(),
                           name='pl-travelogue-archive-month'),
                       url(r'^photo/(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\w{1,2})/(?P<slug>[\-\d\w]+)/$',
                           PhotoDateDetailOldView.as_view(),
                           name='pl-photo-detail'),
                       url(r'^photo/(?P<year>\d{4})/(?P<month>[a-z]{3})/(?P<day>\w{1,2})/$',
                           PhotoDayArchiveOldView.as_view(),
                           name='pl-photo-archive-day'),
                       url(r'^photo/(?P<year>\d{4})/(?P<month>[a-z]{3})/$',
                           PhotoMonthArchiveOldView.as_view(),
                           name='pl-photo-archive-month')
                       )

TripMapR/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.views.generic import TemplateView

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$',  # noqa
        TemplateView.as_view(template_name='pages/home.html'),
        name="home"),
    url(r'^about/$',
        TemplateView.as_view(template_name='pages/about.html'),
        name="about"),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    # User management
    url(r'^users/', include("users.urls", namespace="users")),
    url(r'^accounts/', include('allauth.urls')),

    # Uncomment the next line to enable avatars
    url(r'^avatar/', include('avatar.urls')),

    # Your stuff: custom urls go here

    #travelogue URL 
    url(r'^travelogue/', include('travelogue.urls', namespace='travelogue')),

) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

TripMapR/travelogue/views.py
import warnings

from django.conf import settings
from django.views.generic.dates import ArchiveIndexView, DateDetailView, DayArchiveView, MonthArchiveView, \
    YearArchiveView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.base import RedirectView
from django.core.urlresolvers import reverse

from .models import Photo, Travelogue

# Number of galleries to display per page.
GALLERY_PAGINATE_BY = getattr(settings, 'PHOTOLOGUE_GALLERY_PAGINATE_BY', 20)

if GALLERY_PAGINATE_BY != 20:
    warnings.warn(
        DeprecationWarning('PHOTOLOGUE_GALLERY_PAGINATE_BY setting will be removed in Photologue 3.2'))

# Number of photos to display per page.
PHOTO_PAGINATE_BY = getattr(settings, 'PHOTOLOGUE_PHOTO_PAGINATE_BY', 20)

if PHOTO_PAGINATE_BY != 20:
    warnings.warn(
        DeprecationWarning('PHOTOLOGUE_PHOTO_PAGINATE_BY setting will be removed in Photologue 3.2'))

# Travelogue views.


class TravelogueListView(ListView):
    queryset = Travelogue.objects.on_site().is_public()
    paginate_by = GALLERY_PAGINATE_BY

    def get_context_data(self, **kwargs):
        context = super(TravelogueListView, self).get_context_data(**kwargs)
        if self.kwargs.get('deprecated_pagination', False):
            warnings.warn(
                DeprecationWarning('Page numbers should now be passed via a page query-string parameter.'
                                   ' The old style "/page/n/"" will be removed in Photologue 3.2.'))
        return context


class TravelogueDetailView(DetailView):
    queryset = Travelogue.objects.on_site().is_public()


class TravelogueDateView(object):
    queryset = Travelogue.objects.on_site().is_public()
    date_field = 'date_added'
    allow_empty = True


class TravelogueDateDetailView(TravelogueDateView, DateDetailView):
    pass


class TravelogueArchiveIndexView(TravelogueDateView, ArchiveIndexView):
    pass


class TravelogueDayArchiveView(TravelogueDateView, DayArchiveView):
    pass


class TravelogueMonthArchiveView(TravelogueDateView, MonthArchiveView):
    pass


class TravelogueYearArchiveView(TravelogueDateView, YearArchiveView):
    make_object_list = True

# Photo views.


class PhotoListView(ListView):
    queryset = Photo.objects.on_site().is_public()
    paginate_by = PHOTO_PAGINATE_BY

    def get_context_data(self, **kwargs):
        context = super(PhotoListView, self).get_context_data(**kwargs)
        if self.kwargs.get('deprecated_pagination', False):
            warnings.warn(
                DeprecationWarning('Page numbers should now be passed via a page query-string parameter.'
                                   ' The old style "/page/n/"" will be removed in Photologue 3.2'))
        return context


class PhotoDetailView(DetailView):
    queryset = Photo.objects.on_site().is_public()


class PhotoDateView(object):
    queryset = Photo.objects.on_site().is_public()
    date_field = 'date_added'
    allow_empty = True


class PhotoDateDetailView(PhotoDateView, DateDetailView):
    pass


class PhotoArchiveIndexView(PhotoDateView, ArchiveIndexView):
    pass


class PhotoDayArchiveView(PhotoDateView, DayArchiveView):
    pass


class PhotoMonthArchiveView(PhotoDateView, MonthArchiveView):
    pass


class PhotoYearArchiveView(PhotoDateView, YearArchiveView):
    make_object_list = True


# Deprecated views.

class DeprecatedMonthMixin(object):

    """Representation of months in urls has changed from a alpha representation ('jan' for January)
    to a numeric representation ('01' for January).
    Properly deprecate the previous urls."""

    query_string = True

    month_names = {'jan': '01',
                   'feb': '02',
                   'mar': '03',
                   'apr': '04',
                   'may': '05',
                   'jun': '06',
                   'jul': '07',
                   'aug': '08',
                   'sep': '09',
                   'oct': '10',
                   'nov': '11',
                   'dec': '12', }

    def get_redirect_url(self, *args, **kwargs):
        print('a')
        warnings.warn(
            DeprecationWarning('Months are now represented in urls by numbers rather than by '
                               'their first 3 letters. The old style will be removed in Photologue 3.2.'))


class TravelogueDateDetailOldView(DeprecatedMonthMixin, RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        super(TravelogueDateDetailOldView, self).get_redirect_url(*args, **kwargs)
        return reverse('travelogue:travelogue-detail', kwargs={'year': kwargs['year'],
                                                            'month': self.month_names[kwargs['month']],
                                                            'day': kwargs['day'],
                                                            'slug': kwargs['slug']})


class TravelogueDayArchiveOldView(DeprecatedMonthMixin, RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        super(TravelogueDayArchiveOldView, self).get_redirect_url(*args, **kwargs)
        return reverse('travelogue:travelogue-archive-day', kwargs={'year': kwargs['year'],
                                                                 'month': self.month_names[kwargs['month']],
                                                                 'day': kwargs['day']})


class TravelogueMonthArchiveOldView(DeprecatedMonthMixin, RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        super(TravelogueMonthArchiveOldView, self).get_redirect_url(*args, **kwargs)
        return reverse('travelogue:travelogue-archive-month', kwargs={'year': kwargs['year'],
                                                                   'month': self.month_names[kwargs['month']]})


class PhotoDateDetailOldView(DeprecatedMonthMixin, RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        super(PhotoDateDetailOldView, self).get_redirect_url(*args, **kwargs)
        return reverse('travelogue:photo-detail', kwargs={'year': kwargs['year'],
                                                          'month': self.month_names[kwargs['month']],
                                                          'day': kwargs['day'],
                                                          'slug': kwargs['slug']})


class PhotoDayArchiveOldView(DeprecatedMonthMixin, RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        super(PhotoDayArchiveOldView, self).get_redirect_url(*args, **kwargs)
        return reverse('travelogue:photo-archive-day', kwargs={'year': kwargs['year'],
                                                               'month': self.month_names[kwargs['month']],
                                                               'day': kwargs['day']})


class PhotoMonthArchiveOldView(DeprecatedMonthMixin, RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        super(PhotoMonthArchiveOldView, self).get_redirect_url(*args, **kwargs)
        return reverse('travelogue:photo-archive-month', kwargs={'year': kwargs['year'],
                                                                 'month': self.month_names[kwargs['month']]})

TripMapR/travelogue/templates/travelogue/photo_archive.html
{% extends "travelogue/root.html" %}
{% load i18n %}

{% block title %}{% trans "Latest photos" %}{% endblock %}

{% block content %}

    <div class="row col-lg-12">
        <h1 class="page-header">{% trans "Latest photos" %}</h1>
    </div>

	<div class="row">
		
		<aside class="col-md-2">

			<h4>{% trans "Filter by year" %}</h4>
			<ul>
			{% for date in date_list %}
				<li><a href="{% url 'travelogue:pl-photo-archive-year' date.year %}">{{ date|date:"Y" }}</a></li>
			{% endfor %}
			</ul>

		</aside>

		<main class="col-md-10">
			
			{% if latest %}
			    {% for photo in latest %}
			        <a href="{{ photo.get_absolute_url }}">
			             <img src="{{ photo.get_thumbnail_url }}" class="thumbnail" alt="{{ photo.title }}">
			        </a>
			    {% endfor %}
			{% else %}
				<p>{% trans "No photos were found" %}.</p>
			{% endif %}

		</main>

	</div>

{% endblock %}

TripMapR/travelogue/templates/travelogue/photo_archive_day.html
{% extends "travelogue/root.html" %}
{% load i18n %}

{% block title %}{% blocktrans with show_day=day|date:"d F Y" %}Photos for {{ show_day }}{% endblocktrans %}{% endblock %}

{% block content %}

    <div class="row col-lg-12">
        <h1 class="page-header">{% blocktrans with show_day=day|date:"d F Y" %}Photos for {{ show_day }}{% endblocktrans %}</h1>
    </div>

	{% if object_list %}
		<div class="row col-lg-12">
		    {% for photo in object_list %}
		        <a href="{{ photo.get_absolute_url }}">
		             <img src="{{ photo.get_thumbnail_url }}" class="thumbnail" alt="{{ photo.title }}">
		        </a>
		    {% endfor %}
		</div>
	{% else %}
		<p>{% trans "No photos were found" %}.</p>
	{% endif %}

    <div><a href="{% url 'travelogue:photo-archive-month' day.year day|date:"m"|lower %}" class="btn btn-default">{% trans "View all photos for month" %}</a></div>

{% endblock %}

TripMapR/travelogue/templates/travelogue/photo_archive_month.html
{% extends "photologue/root.html" %}
{% load i18n %}

{% block title %}{% blocktrans with show_month=month|date:"F Y" %}Photos for {{ show_month }}{% endblocktrans %}{% endblock %}

{% block content %}

    <div class="row col-lg-12">
        <h1 class="page-header">{% blocktrans with show_month=month|date:"F Y" %}Photos for {{ show_month }}{% endblocktrans %}</h1>
    </div>

    <div class="row">

        <aside class="col-md-2">

            <h4>{% trans "Filter by day" %}</h4>
            <ul>
            {% for date in date_list %}
                <li><a href="{% url 'photologue:photo-archive-day' date.year date|date:"m"|lower date.day %}">{{ date|date:"d" }}</a></li>
            {% endfor %}
            </ul>

        </aside>

        <main class="col-md-10">

    		{% if object_list %}
    			<div class="row col-lg-12">
    			    {% for photo in object_list %}
    			        <a href="{{ photo.get_absolute_url }}">
    			             <img src="{{ photo.get_thumbnail_url }}" class="thumbnail" alt="{{ photo.title }}">
    			        </a>
    			    {% endfor %}
    			</div>
    		{% else %}
    			<p>{% trans "No photos were found" %}.</p>
    		{% endif %}

            <div><a href="{% url 'photologue:pl-photo-archive-year' month.year %}" class="btn btn-default">{% trans "View all photos for year" %}</a></div>

        </main>

    </div>
    
{% endblock %}

TripMapR/travelogue/templates/travelogue/photo_archive_year.html
{% extends "travelogue/root.html" %}
{% load i18n %}

{% block title %}{% blocktrans with show_year=year|date:"Y" %}Photos for {{ show_year }}{% endblocktrans %}{% endblock %}


{% block content %}

    <div class="row col-lg-12">
        <h1 class="page-header">{% blocktrans with show_year=year|date:"Y" %}Photos for {{ show_year }}{% endblocktrans %}</h1>
    </div>

	<div class="row">

		<aside class="col-md-2">

			<h4>{% trans "Filter by month" %}</h4>
			<ul>
			{% for date in date_list %}
				<li><a href="{% url 'travelogue:photo-archive-month' date.year date|date:"m"|lower %}">{{ date|date:"F" }}</a></li>
			{% endfor %}
			</ul>

		</aside>

		<main class="col-md-10">

			{% if object_list %}
				<div class="row col-lg-12">
				    {% for photo in object_list %}
				        <a href="{{ photo.get_absolute_url }}">
				             <img src="{{ photo.get_thumbnail_url }}" class="thumbnail" alt="{{ photo.title }}">
				        </a>
				    {% endfor %}
				</div>
			{% else %}
				<p>{% trans "No photos were found" %}.</p>
			{% endif %}

		    <div><a href="{% url 'travelogue:pl-photo-archive' %}" class="btn btn-default">{% trans "View all photos" %}</a></div>

		</main>

	</div>

{% endblock %}

TripMapR/travelogue/templates/travelogue/photo_detail.html
{% extends "travelogue/root.html" %}
{% load travelogue_tags i18n %}

{% block title %}{{ object.title }}{% endblock %}

{% block content %}

    <div class="row col-lg-12">
        <h1 class="page-header">{{ object.title }}</h1>
        <p class="muted"><small>{% trans "Published" %} {{ object.date_added }}</small></p>
    </div>

    <div class="row">
        <div class="col-md-6">
		    {% if object.caption %}<p>{{ object.caption|safe }}</p>{% endif %}
		    <a href="{{ object.image.url }}">
		        <img src="{{ object.get_display_url }}" class="thumbnail" alt="{{ object.title }}">
		    </a>
        </div>
        <div class="col-md-6">
            {% if object.public_travelogues %}
                <p>{% trans "This photo is found in the following galleries" %}:</p>
                <table>
                    {% for travelogue in object.public_travelogues %}
                        <tr>
                            <td>{% previous_in_travelogue object travelogue %}</td>
	                        <td class="text-center"><a href="{{ travelogue.get_absolute_url }}">{{ travelogue.title }}</a></td>
	                        <td>{% next_in_travelogue object travelogue %}</td>
                        </tr>
					{% endfor %}
				</table>
			{% endif %}
        </div>
    </div>

{% endblock %}

TripMapR/travelogue/templates/travelogue/photo_list.html
{% extends "travelogue/root.html" %}
{% load i18n %}

{% block title %}{% trans "All photos" %}{% endblock %}

{% block content %}

    <div class="row col-lg-12">
        <h1 class="page-header">{% trans "All photos" %}</h1>
    </div>

	{% if object_list %}
		<div class="row col-lg-12">
		    {% for photo in object_list %}
		        <a href="{{ photo.get_absolute_url }}">
		             <img src="{{ photo.get_thumbnail_url }}" class="thumbnail" alt="{{ photo.title }}">
		        </a>
		    {% endfor %}
		</div>
	{% else %}
		<div class="row">{% trans "No photos were found" %}.</div>
	{% endif %}

	{% include "travelogue/includes/paginator.html" %}

{% endblock %}

TripMapR/travelogue/templates/travelogue/root.html
{% extends "base.html" %}

TripMapR/travelogue/templates/travelogue/travelogue_archive.html
{% extends "travelogue/root.html" %}
{% load i18n %}

{% block title %}{% trans "Latest photo galleries" %}{% endblock %}

{% block content %}

    <div class="row col-lg-12">
        <h1 class="page-header">{% trans "Latest traveloges" %}</h1>
    </div>

	<div class="row">
	
		<aside class="col-md-2">

			<h4>{% trans "Filter by year" %}</h4>
			<ul>
			{% for date in date_list %}
				<li><a href="{% url 'travelogue:pl-travelogue-archive-year' date.year %}">{{ date|date:"Y" }}</a></li>
			{% endfor %}
			</ul>

		</aside>

		<main class="col-md-10">
			
			{% if latest %}
			    {% for travelogue in latest %}
			    	{% include "travelogue/includes/travelogue_sample.html" %}
			    {% endfor %}
			{% else %}
			    <p>{% trans "No traveloges were found" %}.</p>
			{% endif %}
			
		</main>

	</div>
	
{% endblock %}

TripMapR/travelogue/templates/travelogue/travelogue_archive_day.html
{% extends "travelogue/root.html" %}
{% load i18n %}

{% block title %}{% blocktrans with show_day=day|date:"d F Y" %}Galleries for {{ show_day }}{% endblocktrans %}{% endblock %}

{% block content %}

    <div class="row col-lg-12">
        <h1 class="page-header">{% blocktrans with show_day=day|date:"d F Y" %}Galleries for {{ show_day }}{% endblocktrans %}</h1>
    </div>

    <div class="row col-lg-12">
        {% if object_list %}
            {% for gallery in object_list %}
                {% include "travelogue/includes/gallery_sample.html" %}
            {% endfor %}
        {% else %}
            <p>{% trans "No galleries were found." %}</p>
        {% endif %}
    </div>
    
    <div><a href="{% url 'travelogue:travelogue-archive-month' day.year day|date:"m"|lower %}" class="btn btn-default">{% trans "View all galleries for month" %}</a></div>

{% endblock %}

TripMapR/travelogue/templates/travelogue/travelogue_archive_month.html
{% extends "photologue/root.html" %}
{% load i18n %}

{% block title %}{% blocktrans with show_month=month|date:"F Y" %}Galleries for {{ show_month }}{% endblocktrans %}{% endblock %}

{% block content %}

    <div class="row col-lg-12">
        <h1 class="page-header">{% blocktrans with show_month=month|date:"F Y" %}Galleries for {{ show_month }}{% endblocktrans %}</h1>
    </div>

    <div class="row">

        <aside class="col-md-2">

            <h4>{% trans "Filter by day" %}</h4>
            <ul>
            {% for date in date_list %}
                <li><a href="{% url 'photologue:travelogue-archive-day' date.year date|date:"m"|lower date.day %}">{{ date|date:"d" }}</a></li>
            {% endfor %}
            </ul>

        </aside>

        <main class="col-md-10">

            {% if object_list %}
                {% for travelogue in object_list %}
                    {% include "photologue/includes/travelogue_sample.html" %}
                {% endfor %}
            {% else %}
                <p>{% trans "No travelogues were found." %}</p>
            {% endif %}

            <div><a href="{% url 'photologue:pl-travelogue-archive-year' month.year %}" class="btn btn-default">{% trans "View all galleries for year" %}</a></div>

        </main>

    </div>

{% endblock %}

TripMapR/travelogue/templates/travelogue/travelogue_archive_year.html
{% extends "travelogue/root.html" %}
{% load i18n %}

{% block title %}{% blocktrans with show_year=year|date:"Y" %}Galleries for {{ show_year }}{% endblocktrans %}{% endblock %}

{% block content %}

    <div class="row col-lg-12">
        <h1 class="page-header">{% blocktrans with show_year=year|date:"Y" %}Galleries for {{ show_year }}{% endblocktrans %}</h1>
    </div>

	<div class="row">

		<aside class="col-md-2">

			<h4>{% trans "Filter by month" %}</h4>
			<ul>
				{% for date in date_list %}
					<li><a href="{% url 'travelogue:travelogue-archive-month' date.year date|date:"m"|lower %}">{{ date|date:"F" }}</a></li>
				{% endfor %}
			</ul>

		</aside>

		<main class="col-md-10">

			{% if object_list %}
				{% for travelogue in object_list %}
			        {% include "travelogue/includes/travelogue_sample.html" %}
			    {% endfor %}
			{% else %}
			    <p>{% trans "No galleries were found." %}</p>
			{% endif %}

		    <div><a href="{% url 'travelogue:pl-travelogue-archive' %}" class="btn btn-default">{% trans "View all galleries" %}</a></div>

		</main>

	</div>

{% endblock %}

TripMapR/travelogue/templates/travelogue/travelogue_detail.html
{% extends "travelogue/root.html" %}
{% load i18n %}

{% block title %}{{ travelogue.title }}{% endblock %}

{% block content %}

	<div class="row col-lg-12">
        <h1 class="page-header">{{ travelogue.title }}</h1>
        <p class="muted"><small>{% trans "Published" %} {{ travelogue.date_added }}</small></p>        
        {% if travelogue.description %}{{ travelogue.description|safe }}{% endif %}
	    {% for photo in travelogue.public %}
	        <a href="{{ photo.get_absolute_url }}">
	             <img src="{{ photo.get_thumbnail_url }}" class="thumbnail" alt="{{ photo.title }}">
	        </a>
	    {% endfor %}
        <div><a href="{% url 'travelogue:travelogue-list' %}" class="btn btn-default">{% trans "View all galleries" %}</a></div>
	</div>

{% endblock %}

TripMapR/travelogue/templates/travelogue/travelogue_list.html
{% extends "travelogue/root.html" %}
{% load i18n %}

{% block title %}{% trans "All travelogues" %}{% endblock %}

{% block content %}

    <div class="row col-lg-12">
        <h1 class="page-header">{% trans "All travelogues" %}</h1>
    </div>

    {% if object_list %}
        {% for travelogue in object_list %}
            <div class="row col-lg-12">
                <h2><a href="{{ travelogue.get_absolute_url }}">{{ travelogue.title }}</a></h2>
                <p class="muted"><small>{% trans "Published" %} {{ travelogue.date_added }}</small></p>
                {% if travelogue.description %}<p>{{ travelogue.description|safe }}</p>{% endif %}
                {% for photo in travelogue.sample %}
                    <a href="{{ photo.get_absolute_url }}">
                         <img src="{{ photo.get_thumbnail_url }}" class="thumbnail" alt="{{ photo.title }}">
                    </a>
                {% endfor %}
            </div>
        {% endfor %}
    {% else %}
        <div class="row col-lg-12">{% trans "No travelogues were found" %}.</div>
    {% endif %}

    {% include "travelogue/includes/paginator.html" %}
    
{% endblock %}